### ISSUE TITLE
if string smaller then truncate options its removed completely

### ISSUE THREAD

**Issue by vmachacek** [austinthedeveloper/angular-truncate-pipes#1]
when I use `| characters:5`
I get 
```
Nyepi...
Nyepi...
Nyepi...
boat...
Dear...
```
and if I use `| characters:100`

I get 
```

 
 
 
Dear Vojta Machacek,    Thank you for your email and inquiry.    We would like to inform that we do...
```

The items which are smaller than truncating parameter are totally omitted from the page.  That makes this plugin very much useless..

Did I missed something?

**Comment by austinthedeveloper** [comment]
I'm not sure if I understand the problem. What is the end result supposed to look like? If I'm understanding your code, the string below is limited to 100 characters and it looks like that's where it cuts off.

Were you wanting the `words` pipe instead?

**Comment by vmachacek** [comment]
Look at the first line of first box of example, than look at the first line of second box of example. You can see in the second box there is nothing. Which is the problem. Got it now?
